### ISSUE TITLE
It's impossible to tell how to download this

### ISSUE THREAD

**Issue by cyllu2** [jssor/slider#117]
Yeah, there is a download link, but it only downloads some zip file and the minfied version is 52 kb there, not 16kb as claimed. It's impossible to know what version to install if you want only a certain gallery. What's "jssor.player.ytiframe" or what's the difference between "jssor.slider.mini.js" and "jssor.slider.min.js"?

One file is 90 kb big, none is actually 16kb. I'm interested in the Image Gallery With Vertical Thumbnail, by the way.

**Comment by jssor** [comment]
The `jssor.compress.exe` is a smart js compressor especially for jssor javascript library.

Open `example-no-jquery`, you will see `simple-slider.compress.bat`, which demonstrates the typical usage of the compressor. After you run the bat, you will get `simple-slider.html`, the final javascript code is 19.7KB.

The `16kb` you saw is in a document which hasn't been updated for a long time.

Reference: http://www.jssor.com/development/tool-jssor-compress-exe.html

Thanks for your interest!
Kind Regards

**Comment by cyllu2** [comment]
I don't care about "simple slider". The file gets 41 kb when compressed.

**Comment by jssor** [comment]
jssor.slider.mini.js is jquery version, jssor.slider.min.js is no jquery version. Both work the same, you can determine which one to include. You'd include jssor.player.ytiframe.js if you want to embed youtube video. See `examples-jquery\video-gallery.source.html'

**Comment by jssor** [comment]
Re: Literally no such thing as simple-slider.html, and I don't know what it is. Since when did I want an html file anyway?

No worry, you can use jssor.slider.mini.j or jssor.slider.min.js to use it simply. But if you want to reduce js code to minimum size, you can compress it in the manner that I stated in the previous answer.

Btw, the compression is not only for `simple.slider.source.html`, but also for any other html files. And also, you can compress single/multiple js file(s) as well.

**Comment by jssor** [comment]
One more thing, if you want to embed slider in ebay listing, you'd get it (deep) compressed first.
