### ISSUE TITLE
IE8 the whole page can't scroll or even responseless

### ISSUE THREAD

**Issue by WynnLin** [jssor/slider#220]
as the title said.
In IE8 the browser seems breaked when load jssor.slider.min.js
after you narrow window or right mouse clicked, it becomed normal
you can check your website [https://www.jssor.com/](https://www.jssor.com/)
sorry for my poor english, i wish you can understand the issue

**Comment by jssor** [comment]
Re: In IE8 the browser seems breaked when load jssor.slider.min.js
It works on IE 8 with no problem.
Please run jssor slider on IE 8 instead of the whole home page of jssor.com.

jssor.com home page works ok with IE 8 except minor issue from abg.js (which comes with google ad service), please ignore this issue.
